# Generated by Django 3.2.12 on 2024-02-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronic', 'Electronic'), ('fashion', 'Fashion'), ('home_appliance', 'Home Appliance'), ('books', 'Books'), ('toys', 'Toys'), ('beauty', 'Beauty'), ('sports', 'Sports'), ('outdoor', 'Outdoor'), ('automotive', 'Automotive'), ('grocery', 'Grocery'), ('health', 'Health'), ('furniture', 'Furniture'), ('music', 'Music'), ('movies', 'Movies'), ('pets', 'Pets'), ('jewelry', 'Jewelry'), ('stationery', 'Stationery'), ('tools', 'Tools'), ('food', 'Food'), ('drink', 'Drink')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
