# Generated by Django 3.2.12 on 2024-02-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20240202_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronic', 'Electronic'), ('fashion', 'Fashion'), ('home_appliance', 'Home Appliance'), ('books', 'Books'), ('toys', 'Toys'), ('beauty', 'Beauty'), ('sports', 'Sports'), ('outdoor', 'Outdoor'), ('automotive', 'Automotive'), ('grocery', 'Grocery'), ('health', 'Health'), ('furniture', 'Furniture'), ('jewelry', 'Jewelry'), ('stationery', 'Stationery'), ('tools', 'Tools'), ('food', 'Food')], max_length=20),
        ),
    ]
